config/routes.rb
DevopsKeychain::Application.routes.draw do
  devise_for :users

     root 'application#root'

     get 'key' => 'privatekeys#new'
     get 'key/create' => 'privatekeys#create'
     get 'admin' => 'users#list'
     get 'users/new' => 'users#new'
     get 'users/create' => 'users#create'
     get 'users' => 'users#show'
     get 'deployments/new' => 'deployment#new'
     get 'deployments/:id' => 'deployment#show'
     post 'secure' => 'secure_content#show'

     post 'environment/update' => 'environment#update'
     post 'secure_content/update' => 'secure_content#update'
     post 'secure_content/create'  => 'secure_content#create'
     post 'secure_content/delete'  => 'secure_content#delete'
     post 'deployment/create'  => 'deployment#create'
     post 'environment/create' => 'environment#create'

end

app/models/deployment.rb
class Deployment < ActiveRecord::Base

  validates :name, presence: true , allow_blank: false

  has_many :permissions, dependent: :destroy
  has_many :environments, dependent: :destroy
  has_many :users, through: :permissions

end

app/models/environment.rb
class Environment < ActiveRecord::Base

  validates :name, presence: true , allow_blank: false
  validates :deployment_id, presence: true , allow_blank: false

  belongs_to :deployment
  has_many :secure_content, dependent: :destroy

end

app/models/permission.rb
class Permission < ActiveRecord::Base

  belongs_to :user
  belongs_to :deployment

end

app/models/secure_content.rb
class SecureContent < ActiveRecord::Base

  attr_encrypted :content

  validates :encrypted_content, :symmetric_encryption => true

  belongs_to :environment

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :permissions
  has_many :deployments, through: :permissions


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  def has_permission?(user_id,deployment_id)
  		return !Permission.find_by_user_id_and_deployment_id(user_id, deployment_id ).nil?
  end

  def forbidden
	render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
  end

end

app/controllers/deployment_controller.rb
class DeploymentController < ApplicationController

	def show

		@deployment = Deployment.find_by_id(params[:id])

		if(@deployment.nil?)
			flash[:alert] = "That deployment does not exist"
			redirect_to "/"
			return
		end

		if(!has_permission?(current_user.id, @deployment.id))
			forbidden
			return
		end

	end

	def new
		@users = User.all
	end

	def create

		if(params[:name].strip() === "")
			flash[:alert] = "A deployment name cannot be blank"
			redirect_to :back
			return
		end

		@deployment = Deployment.new(name: params[:name], description: params[:description])

		begin
			@deployment.save
		rescue ActiveRecord::RecordNotUnique => e
			flash[:alert] = "A Deployment called '#{params[:name]}' already exists."
			redirect_to :back
			return
		end

		params.keys.find_all{|item| item.start_with? "permission_" }.each do |email|
			@user = User.find_by(email: email.sub(/^permission_*/,"") )
			Permission.create(:user_id => @user.id, :deployment_id => @deployment.id)
		end

		Permission.create(:user_id => current_user.id, :deployment_id => @deployment.id)

		redirect_to "/deployments/#{@deployment.id}"

	end

end

app/controllers/environment_controller.rb
class EnvironmentController < ApplicationController

	def update

		require 'base64'

		key_pair = generate_keys()

		environment = Environment.find_by(id: params[:environment][:id])
		environment.update(public_key: Base64.encode64(key_pair[0]))

		filename = "#{environment.deployment.name}-#{environment.name}.pem"

		send_data key_pair[1], :filename => filename

	end


	def generate_keys()

		require 'openssl'
		rsa_key = OpenSSL::PKey::RSA.new(2048)

		cipher =  OpenSSL::Cipher::Cipher.new('des3')

		private_key = rsa_key.to_pem(cipher,'password')
		public_key = rsa_key.public_key.to_pem
		key_pair = [public_key,private_key]

		return key_pair
		
	end

	def create

		if(!has_permission?(current_user.id,params[:deployment_id]))
			forbidden
			return
		end

		if(params[:name].strip() === "")
			flash[:alert] = "An environment name cannot be blank"
			redirect_to :back
			return
		end

		@environment = Environment.new(name: params[:name], deployment_id: params[:deployment_id])

		begin
			@environment.save
		rescue ActiveRecord::RecordNotUnique => e
			flash[:alert] = "An environment called '#{params[:name]}' already exists."
		end

		redirect_to :back
	end


end

app/controllers/secure_content_controller.rb
class SecureContentController < ApplicationController

  skip_before_filter :verify_authenticity_token
  skip_before_filter :authenticate_user!

  def show

    begin
      deployment = Deployment.find_by(name: params[:deployment])
      environment = Environment.find_by_name_and_deployment_id(params[:environment], deployment.id)
      content = SecureContent.find_by_name_and_environment_id(params[:securecontent], environment.id)[:encrypted_content]
      if(params[:auth].nil?)
        raise "Missing auth header"
      end  
    rescue
      render :file => "public/400", :status => 400
     return
    end

    keychain_auth = params[:auth]
    public_key = environment[:public_key]

    if( params[:securecontent] === public_decrypt(public_key,keychain_auth))
      send_data public_encrypt(public_key,SymmetricEncryption.decrypt(content))
    else
      render :file => "public/401", :status => :unauthorized
    end

  end

  def update

   password = SecureContent.find_by(:id => params[:secure_content][:id])

    flash[:notice] = "#{password.name} has been successfully updated for the environment #{password.environment.name}."
    password.update(:encrypted_content => SymmetricEncryption.encrypt(params[:secure_content][:content]))
  

    redirect_to :back

end

def delete

   password = SecureContent.find_by(:id => params[:secure_content][:id])

  flash[:notice] = "#{password.name} has been successfully deleted."
  password.destroy()

  redirect_to :back

end


def create

  flash[:notice] = "Added the password: #{params[:environment][:name]}."
  SecureContent.create(:name => params[:environment][:name], :content => params[:environment][:content], :environment_id => params[:environment][:environment_id])

  redirect_to :back

end


  def public_encrypt(key, plaintext_string)

    require 'openssl'
    require 'base64'

    public_key_file = Base64.decode64(key)

    public_key = OpenSSL::PKey::RSA.new(public_key_file)
    encrypted_string = Base64.encode64(public_key.public_encrypt(plaintext_string))

    return encrypted_string

  end

  def public_decrypt (key, encrypted_string)

    require 'openssl'
    require 'base64'

    public_key_file = Base64.decode64(key)
    public_key = OpenSSL::PKey::RSA.new(public_key_file)
    encrypted_string = Base64.decode64(encrypted_string)

    return public_key.public_decrypt(encrypted_string)
  rescue
    return nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		render html: "OK"
	end

	def list
		@users = User.all
	end

	def create
	end

	def show

		
		if(user_signed_in?)
	    @passwords = SecureContent.all #where("owner = ?", current_user[:id])

	end


end

def update
	
	require 'base64'

	key_pair = generate_keys()

	user = User.find_by(email: params[:user][:email])
	user.update(pub_key: Base64.encode64(key_pair[0]))

	send_data key_pair[1], :filename => 'private.pem'

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deployment_helper.rb
module DeploymentHelper
end

app/helpers/environment_helper.rb
module EnvironmentHelper
end

app/helpers/secure_content_helper.rb
module SecureContentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/root.html.erb
Default page. Not sure what to put here.

app/views/deployment/new.html.erb
<% if user_signed_in? %>

   <%= form_tag("/deployment/create", method: "POST") do %>
              <%= label_tag(:name, "Name:") %>
              <%= text_field_tag(:name, "", type: "text") %><br/>
               <%= label_tag(:description, "Description (optional):") %>
              <%= text_field_tag(:description, "", size: '50x10') %>
            
	<h1>Permissions</h1>

	 <table class="table table-striped table-bordered">
		 <tr>
	        <th>Name</th>
	        <th>Read/Write</th>
	      </tr>	
	 	 <% @users.order("email asc").each do |user| %>
	  	 	<tr>
	  	 		<td><%= user.email %></td>
	  	 		<% if user.id === current_user.id %>
	  	 		<td><%= check_box_tag("permission_#{user.email}", 1, true, disabled: true) %></td>
	  	 		<% else %>
	  	 		<td><%= check_box_tag("permission_#{user.email}") %></td>
	  	 		<% end %>
	  	 	
	  	 	</tr>
	  	 <% end %>
	 </table>

   <%= submit_tag("Create", class: "btn btn-primary", style: "width:100px") %>

<% end %>    



<% end %>


<script>
setActive("Deployments")
</script>

app/views/deployment/show.html.erb
<% if user_signed_in? %>
   <div class="col-xs-12 col-sm-6">
    <h1>
       <%= @deployment.name -%>
    </h1>
    <div>
       <%= @deployment.description -%>
    </div>

    <% @deployment.environments.order("name asc").each do |environment| %>
     <h2><%= environment.name -%></h1>
     <table class="table table-striped table-bordered">
      <tr>
        <th>Name</th>
        <th>Password</th>
        <th></th>
      </tr>
 
      <% SecureContent.where(:environment_id => environment.id).order("name asc").each do |password| %>
      <tr>
        <td class="float"><%= password.name %></td>
        <td class="float">

                
        <%= form_for password, url: secure_content_update_path(), method: :post do |f| %>
        <%= f.text_field :content, class: "show_hide", type: "password", value: password.content %>
        <%= f.hidden_field :id %>
        <%= f.submit "Update", class: "btn btn-primary", style: "margin-left:20px;min-width:100px" %>
        <% end %>    
        </td>
        <td>
         <%= form_for password, url: secure_content_delete_path(), method: :post do |f| %>  
         <%= f.hidden_field :id %>
         <%= f.submit "X", class: "btn btn-danger", style: "min-width:100px"%>
         <% end %>    
       


        </td>
      </tr>
      <% end %>
      <tr>
        <td>
        <%= form_for environment, url: secure_content_create_path(), method: :post do |f| %>
        <%= f.text_field :name, value: "" %>
        <%= f.text_field :content, value: "", type: "password" %>
        <%= f.hidden_field :environment_id, value: environment.id %>
        <%= f.submit "Create" %>
        <% end %>
        </td>
      </tr>
   
    </table>

        <%= form_for environment, url: environment_update_path(), method: :post do |f| %>
        <%= f.hidden_field :id %>
        <%= f.hidden_field "deployment", value: @deployment.name %>
        <%= f.submit "Generate new private key" %>
        <% end %>

  <% end %>    
 </div>


             <%= form_tag("/environment/create", method: "POST") do %>
              <%= label_tag(:name, "New Environment:") %>
              <%= text_field_tag(:name, "", type: "text") %><br/>
              <%= hidden_field_tag( :deployment_id, @deployment.id ) %>
              <%= submit_tag("Add", class: "btn btn-primary", style: "width:100px") %>
              <% end %>  
<% end %>


<%- content_for(:js) do -%>
  <%= javascript_include_tag "hideShowPassword.min" -%>
<%- end -%>

  <script>
    $('input.show_hide').hideShowPassword(false, true);
  </script>

<script>
setActive("Deployments")
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevopsKeychain</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Devops Keychain</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--li class="active"><a href="/">Passwords</a></li-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Deployments <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <% if user_signed_in? %>
             <% current_user.deployments.each do |deployment| %>
            <li><a href="/deployments/<%= deployment.id %>"><%= deployment.name %></a></li>
             <% end %>           
            <li class="divider"></li>
            <li><a href="/deployments/new">Create new deployment</a></li>
           <% else %>
               <li><a>Sign in to view Deployments</a></li>
           <% end %>
          </ul>
        </li>
        <% if current_user.try(:admin?) %>
        <li><a href="/admin">Admin</a></li>
         <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
              <li><a><strong><%= current_user.username %></strong></a></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Register", new_user_registration_path  %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/list.html.erb
<% if current_user.try(:admin?) %>
 <div class="col-xs-12">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Username</th>
        <th>Public Key</th>
        <th></th>
      </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
       
        <td>

        <%= form_for user, url: users_update_path(), method: :post do |f| %>
        <%= f.hidden_field :email %>
        <%= f.submit "Generate new private key", onClick: "setTimeout('location.reload(true);', 5000)" %>
        <% end %>


        </td>
      </tr>
    <% end %>
    </table>
  </div>
<% end %>

<script>
setActive("Admin")
</script>

app/views/users/show.html.erb
<% if user_signed_in? %>
  <div class="col-xs-12 col-sm-6">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Name</th>
        <th>Password</th>
      </tr>

    <% @passwords.each do |password| %>
      <tr>
        <td class="float"><%= password.name %></td>
        <td class="float">

                
        <%= form_for password, url: secure_content_update_path(), method: :post do |f| %>
        <%= f.text_field :content, class: "show_hide", type: "password", value: password.content %>
        <%= f.hidden_field :name %>
        <%= f.submit "Update", onClick: "setTimeout('location.reload(true);', 2000)", class: "btn btn-primary", style: "margin-left:20px;min-width:100px" %>
        <%= f.submit "Delete", onClick: "setTimeout('location.reload(true);', 2000)", class: "btn btn-danger", style: "min-width:100px"%>
        <% end %>    
       


        </td>
      </tr>
    <% end %>
    </table>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Password</h3>
      </div>
      <div class="panel-body">
          <%= form_tag("/secure_content/new", method: "POST") do %>
              <%= label_tag(:name, "Name:") %>
              <%= text_field_tag(:name, "", type: "text") %>
              <%= label_tag(:content, "Password:") %>
              <%= text_field_tag(:content, "",class: "show_hide", type: "password") %>
              <%= submit_tag("Create", class: "btn btn-primary", style: "width:100px") %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>


<%- content_for(:js) do -%>
  <%= javascript_include_tag "hideShowPassword.min" -%>
<%- end -%>

  <script>
    $('input.show_hide').hideShowPassword(false, true);
  </script>

<script>
setActive("Passwords")
</script>